#' Reclustering Analysis
#'
#' Performs reclustering and basic visualization
#' of a subsetted Seurat object subset.
#' Subsets are determined based on cell groups.
#'
#' @param title1 Name of cell type(s) being reclustered. This information
#' is used for filenames generated by reclustering analysis.
#' @param so An object of class Seurat.
#' @param rc_type Data set type being reclustered (either "GEX" or "Mult").
#' @param ct_col Column containing cell type information.
#' @param ct Character strings separated by vertical bars "|"
#' indicating cell types to factor in reclustering.
#' The provided Seurat object is then subsetted to include
#' only clusters from the provided group names.
#' @param slot1 Assay from Seurat object subset to use (ex. "RNA").
#' @param md_list A vector of character strings indicating metadata
#' columns for overlaying on a loadings plot.
#' @param prop_list Subset of md_list to use for stratifying cell type
#' proportion columns.
#' @param dim1 Number of dimensions to use in PCA.
#' @param batch_cor Should Harmony based batch correction be performed?
#' @param cor_col Variables to regress out of PCA if batch_cor is TRUE.
#' @param h_w Numeric value for heatmap width (passed to ComplexHeatmap).
#' @param h_h Numeric value for heatmap height (passed to ComplexHeatmap).
#' @param fs_c Numeric value for column fontsize (passed to ComplexHeatmap).
#' @param fs_r Numeric value for row fontsize (passed to ComplexHeatmap).
#' @param cl_c Cluster columns?
#' @param cl_r Cluster rows?
#' @param rot_c Rotation of column names.
#' @param col1 Gradient color scheme to use
#' (must be exactly 4 colors in length).
#' @return A reclustered Seurat Object with summary plots, proportion tables,
#' and marker gene lists.
#' @examples
#'
#' # d_recluster <- sc_recluster(
#' #   title1 = "basal",
#' #   so = d_gene,
#' #   rc_type = "GEX",
#' #   ct_col = "CellType",
#' #   ct = "Bas|Cyc|Sup",
#' #   slot1 = "RNA",
#' #   md_list = c("Code", "Airway", "Batch"),
#' #   prop_list = c("Code", "Airway"),
#' #   dim1 = 30,
#' #   batch_cor = TRUE,
#' #   cor_col = c("Batch", "Code"),
#' #   h_w = 12,
#' #   h_h = 39,
#' #   fs_c = 10,
#' #   fs_r = 9,
#' #   cl_c = TRUE,
#' #   cl_r = TRUE,
#' #   rot_c = 45,
#' #   col1 = col_hmap
#' # )
#'
#' @export
sc_recluster <- function(
  title1,
  so,
  rc_type,
  ct_col,
  ct,
  slot1,
  md_list,
  prop_list,
  dim1,
  batch_cor,
  cor_col,
  h_w,
  h_h,
  fs_c,
  fs_r,
  cl_c,
  cl_r,
  rot_c,
  col1
) {
  # Load objects
  d <- so
  ctn <- ct_col
  ctf <- ct

  # Reclustering of traditional scRNA-Seq data
  if(rc_type == "GEX") { # nolint
    SeuratObject::DefaultAssay(d) <- slot1
    # subset
    d <- d[, grepl(ctf, as.character(d@meta.data[[ctn]]))]
    # Re-run dimension reduction on object subset
    options(future.globals.maxSize = 10000 * 1024 ^ 2)
    d <- Seurat::SCTransform(d, new.assay.name = "sct")
    # Run PCA
    d <- Seurat::RunPCA(d)
    d_pca <- sc_pca_plot( # nolint
      d,
      c(md_list, ct_col)
    )
    ggplot2::ggsave(
      paste("analysis/recluster/recluster", title1, "pca.panel.png", sep = "."),
      d_pca,
      width = 42,
      height = 12,
      dpi = 700
    )
    ## Run Harmony if batch effect exists
    if(batch_cor == TRUE) { # nolint
      d <- harmony::RunHarmony(
        d,
        assay.use = "sct",
        group.by.vars = cor_col,
        reduction.use = "pca",
        reduction.save = "pca.cor",
        project.dim = FALSE
      )
      plot_var_feat <- Seurat::VariableFeaturePlot(
        d,
        assay = "sct"
      )
      plot_dim_load <- Seurat::VizDimLoadings(
        object = d,
        dims = 1:2,
        reduction = "pca"
      )
      plot_elbow <- Seurat::ElbowPlot(
        d,
        reduction = "pca.cor",
        ndims = 50
      )
      # Run UMAP
      Seurat::Idents(d) <- ct_col
      d <- Seurat::RunUMAP(
        object = d,
        reduction = "pca.cor",
        dims = 1:dim1,
        n.components = 3
      )
    }
    if(batch_cor == FALSE) { # nolint
      plot_var_feat <- Seurat::VariableFeaturePlot(
        d,
        assay = "sct"
      )
      plot_dim_load <- Seurat::VizDimLoadings(
        object = d,
        dims = 1:2,
        reduction = "pca"
      )
      plot_elbow <- Seurat::ElbowPlot(
        d,
        reduction = "pca.cor",
        ndims = 50
      )
      # Run UMAP
      Seurat::Idents(d) <- ct_col
      d <- Seurat::RunUMAP(
        object = d,
        reduction = "pca",
        dims = 1:dim1,
        n.components = 3
      )
    }
    SeuratObject::DefaultAssay(d) <- "sct"
    d <- Seurat::FindNeighbors(
      d,
      reduction = "umap",
      dims = 1:3,
      verbose = TRUE
    )
    d <- Seurat::FindClusters(
      d,
      cluster.name = "recluster",
      resolution = 0.3
    )
    d_umap1 <- sc_umap_panel( # nolint
      d,
      c(ct_col, md_list, "recluster"),
      "umap"
    )
    ggplot2::ggsave(
      paste(
        "analysis/recluster/recluster",
        title1,
        "umap.panel.png",
        sep = "."
      ),
      d_umap1,
      height = 16,
      width = 32,
      dpi = 400
    )
    # Reclustering QC
    ggplot2::ggsave(
      paste(
        "analysis/recluster/recluster",
        title1,
        "qc.panel.png",
        sep = "."
      ),
      sc_integration_qc(d, "recluster"), # nolint
      width = 24,
      height = 8,
      dpi = 700
    )

    # Marker gene heatmap
    d_hmap <- sc_top10_marker_heatmap_rc( # nolint
      sorc = d,
      asy = "GEX",
      slot1 = "sct",
      cl_var = "recluster",
      h_w = h_w,
      h_h = h_h,
      fs_c = fs_c,
      fs_r = fs_r,
      cl_c = cl_c,
      cl_r = cl_r,
      rot_c = rot_c,
      col1 = col1
    )
    ## Save
    png(
      paste(
        "analysis/recluster/recluster",
        title1,
        "hmap.top10mark.png",
        sep = "."
      ),
      width = 40,
      height = 20,
      units = "cm",
      res = 1800
    )
    print(d_hmap)
    dev.off()

    # Cluster Proportions
    fun_predict_prop <- function(
      x,
      c,
      md
    ) {
      data_pred_prop2 <- setNames(
        dplyr::count(
          x,
          .data[[c]] # nolint
        ),
        c(c, "Total Cells")
      )
      data_pred_prop <- dplyr::count(
        x,
        x[, c(md, c)]
      )
      data_pred_prop <- dplyr::left_join(
        data_pred_prop,
        data_pred_prop2,
        by = c
      )
      data_pred_prop[["Proportion"]] <- round(
        data_pred_prop$n /
          data_pred_prop$`Total Cells`,
        digits = 3
      )
      return(data_pred_prop)
    }
    d <- SeuratObject::AddMetaData(
      d,
      gsub("_.*", "", d@meta.data[["Code"]]),
      col.name = "Code1"
    )
    write.table(
      fun_predict_prop(
        d@meta.data,
        "recluster",
        c(prop_list)
      ),
      paste(
        "analysis/recluster/recluster",
        title1,
        "table.proportions.txt",
        sep = "."
      ),
      sep = "\t",
      row.names = FALSE,
      col.names = TRUE
    )

    ## Save RDS
    saveRDS(
      d,
      paste(
        "analysis/recluster/recluster",
        title1,
        "subset.data.RDS",
        sep = "."
      ),
    )

  }
  return(
    list = c(
      "data" = d,
      "pca_panel" = d_pca,
      "pca_load" = plot_dim_load,
      "pca_feat" = plot_var_feat,
      "pca_elbow" = plot_elbow,
      "umap_panel" = d_umap1,
      "hmap_top10" = d_hmap
    )
  )
}
